version: '3'
services:
  web:
    image: odoo16_ctieg
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - './odoo-web-data:/opt/odoo/data'
      - './modulos:/opt/odoo/extra-addons'
#      - './modulos/enterprise:/mnt/enterprise'
      - './config:/opt/odoo/config'
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - './odoo-db-data:/var/lib/postgresql/data/pgdata'
    restart: always
